question_data = [{"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Gumbo is a stew that originated in Louisiana.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "Science: Gadgets", "type": "boolean", "difficulty": "easy",
                  "question": "The communication protocol NFC stands for Near-Field Control.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The 2005 video game &quot;Call of Duty 2: Big Red One&quot; is not available on PC.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "You could walk from Norway to North Korea while only passing through Russia.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                  "question": "Time on Computers is measured via the EPOX System.", "correct_answer": "False",
                  "incorrect_answers": ["True"]}, {"category": "History", "type": "boolean", "difficulty": "medium",
                                                   "question": "Oxford University is older than the Aztec Empire. ",
                                                   "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
                  "question": "In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "History", "type": "boolean", "difficulty": "easy",
                  "question": "The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Geography", "type": "boolean", "difficulty": "easy",
                  "question": "There is an island in Japan called \u014ckunoshima, A.K.A. &quot;Rabbit Island&quot;, so named because of it&#039;s huge population of rabbits.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
                  "question": "John Williams composed the music for &quot;Star Wars&quot;.", "correct_answer": "True",
                  "incorrect_answers": ["False"]}]
